import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import TaskItem from "../Components/taskItem";
import { useQuery } from "@tanstack/react-query";
import { AuthContext } from "../Context/AuthProvider";
import { useContext } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user } = useContext(AuthContext);

  const {
    data: tasks = [],
    isLoading,
    refetch,
  } = useQuery({
    queryKey: ["tasks"],
    queryFn: async () => {
      try {
        const res = await fetch("https://todo-app-server-rho.vercel.app/tasks");
        const data = await res.json();
        return data;
      } catch (error) {}
    },
  });
  console.log(tasks);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={` `}>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {tasks?.map((t) => (
              <TaskItem key={t._id} t={t} refetch={refetch}>
                {" "}
              </TaskItem>
            ))}

            <TaskItem />
            <TaskItem />
            <TaskItem />
            <TaskItem />
            <TaskItem />
          </div>
        </div>
      </main>
    </>
  );
}
